//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VERITABANI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public string Kullanici_adi { get; set; }
        public string Kullanici_soyadi { get; set; }
        public string Kullanici_parola { get; set; }
        public int Kullanici_id { get; set; }
        public Nullable<int> Kullanici_yas { get; set; }
        public string Kullanici_dogum_yeri { get; set; }
        public string Kullanici_telefon { get; set; }
        public string Kullanici_email { get; set; }
    }
}
